# N.B: Intended for docker's build context to be the project root
FROM my_pnpm_dev:latest

ARG APP_NAME=my_app

# Set work directory
WORKDIR /opt/${APP_NAME:-my_app}

# Install(/update) pnpm + app dependencies
COPY app/package.json .
COPY app/pnpm-lock.yaml .
COPY app/.npmrc .
RUN npm install -g pnpm \
    && pnpm --version\
    && pnpm install

# Copy app source
COPY app/ .

# Expose ports to outside of the container
#   dev port
EXPOSE  3333
#   hot module reload (HMR) port
#   cf. bugfix: https://github.com/vitejs/vite/issues/4116#issuecomment-983261927
EXPOSE 3334

CMD [ "pnpm", "dev:local" ]
